[build]
command = "astro build"
base = "/"
publish = "dist"

# Register the astro-kirby-sync as a Netlify Build Plugin
[[plugins]]
package = "./plugins/astro-kirby-sync"

[build.processing.html]
pretty_urls = false

[build.environment]
NODE_VERSION = "23"

[images]
<<<<<<< HEAD
remote_images = [ "https://cms.kinderlosfrei.matthiashacksteiner.net/media/.*" ]
=======
remote_images = [ "https://cms.baukasten.matthiashacksteiner.net/media/.*" ]
>>>>>>> clean-template-666d3f4a

[dev]
  autoLaunch = false
