function pxToRem(px) {
	return px / 16 + 'rem';
}

module.exports = {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	safelist: [
		'col-span-1',
		'col-span-2',
		'col-span-3',
		'col-span-4',
		'col-span-5',
		'col-span-6',
		'col-span-7',
		'col-span-8',
		'col-span-9',
		'col-span-10',
		'col-span-11',
		'col-span-12',
		'col-span-full',
		'col-start-1',
		'col-start-2',
		'col-start-3',
		'col-start-4',
		'col-start-5',
		'col-start-6',
		'col-start-7',
		'col-start-8',
		'col-start-9',
		'col-start-10',
		'col-start-11',
		'col-start-12',
		'lg:col-span-1',
		'lg:col-span-2',
		'lg:col-span-3',
		'lg:col-span-4',
		'lg:col-span-5',
		'lg:col-span-6',
		'lg:col-span-7',
		'lg:col-span-8',
		'lg:col-span-9',
		'lg:col-span-10',
		'lg:col-span-11',
		'lg:col-span-12',
		'lg:col-span-full',
		'lg:col-start-1',
		'lg:col-start-2',
		'lg:col-start-3',
		'lg:col-start-4',
		'lg:col-start-5',
		'lg:col-start-6',
		'lg:col-start-7',
		'lg:col-start-8',
		'lg:col-start-9',
		'lg:col-start-10',
		'lg:col-start-11',
		'lg:col-start-12',
		'w-full',
	],
	theme: {
		screens: {
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1280px',
			'2xl': '1440px',
			'3xl': '1920px',
		},
		container: {
			padding: {
				DEFAULT: 'var(--grid-margin-mobile)',
				sm: 'var(--grid-margin-mobile)',
				lg: 'var(--grid-margin-desktop)',
				xl: 'var(--grid-margin-desktop)',
				'2xl': 'var(--grid-margin-desktop)',
				'3xl': 'var(--grid-margin-desktop)',
			},
			center: true,
		},

		deliciousHamburgers: {
			// size: '19px',
			// width: '24px',
			// barSpacing: '16px',
			// borderRadius: '2px',
			// thickness: '2px',
			// color: '#000',
			// colorLight: '#fff',
			// padding: '4px',
			animationSpeed: 1,
		},
		extend: {
			colors: {
				primary: 'var(--color-primary)',
				secondary: 'var(--color-secondary)',
				tertiary: 'var(--color-tertiary)',
				white: 'var(--color-white)',
				black: 'var(--color-black)',
				transparent: 'var(--color-transparent)',
			},
			spacing: {
				'screen-1/2': '50vh',
			},
			height: {
				screen: ['100vh /* fallback for Opera, IE and etc. */', '100svh'],
			},
			minHeight: {
				screen: ['100vh /* fallback for Opera, IE and etc. */', '100svh'],
			},
		},
	},
	plugins: [require('tailwindcss-delicious-hamburgers')],
};
